webserver:
  build:
    context: ./Streamchat.Webserver
  container_name: streamchat_webserver
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./Streamchat.Webserver/app.config.json:/usr/src/app/app.config.json
    - ./Streamchat.Webserver/unterstadistycs.sytes.net-chain.pem:/usr/src/app/unterstadistycs.sytes.net-chain.pem
    - ./Streamchat.Webserver/unterstadistycs.sytes.net-key.pem:/usr/src/app/unterstadistycs.sytes.net-key.pem