version: '3.8'

services:
  environment:
  - MONGO_URI=mongodb://mongo:27017
  webserver:
    build:
      context: .
    container_name: streamchat_webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../sec/app.config.json:/usr/src/app/app.config.json
      - ../sec/unterstadistycs.sytes.net-chain.pem:/usr/src/app/unterstadistycs.sytes.net-chain.pem
      - ../sec/unterstadistycs.sytes.net-key.pem:/usr/src/app/unterstadistycs.sytes.net-key.pem